services:
  backend:
    image: esthercl/backend:latest
    platform: linux/amd64
    ports:
      - "8000:8000"

  frontend:
    image: esthercl/frontend:latest
    platform: linux/amd64
    ports:
      - "8080:80"
